description: hamcrest-java (master)
base-diff-url: https://github.com/hamcrest/JavaHamcrest/commit/
write-json-diffs: false
redactions: 
- "@2aa0e9f1-8e24-0410-adc4-1b6a3a6e65e2"
testable-file-suffixes: 
- .java